language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- nightly
install: true
script: echo hello
deploy:
  provider: pypi
  user: davidsulpy
  password:
    secure: a/daKGCkdsiWucEjAY+hbLsov1Ntt3CIEscgQpyAB+KBxaVVbQfQQ8NVjLSMbzblBAiVgClHjZJTWBoY5Xs85rytSfEOUcBNAq6Qi/IHswwyiR8VSq3jLMqEDKqR0KZv/vg+vX/KPw4oD+ShLVPNuecmMFNQu2vNWle1uggtOE8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: initialstate/python_appender
    branch: master
    python: '3.5'
    skip_existing: true
notifications:
  slack:
    secure: rAnXefiLNiVD2XtRHei42YG9JNDcbzcK/4ZFH2eVMIvYuWIhaeHUeO6kw/A5kGlnk862trhWfvqu6I+Fg0eH040O7DYpRaUDnXOCzLR1zGA5M8qN71uYZsFppPnpDH0TzpVMnIrv2xyjik4zkonJCuAVrLgmLBVCHIt2Bqvs06w=
