#!/bin/bash

echo "Beginning ISStreamer Python Easy Installation!"
echo "This may take a couple minutes to install, grab some coffee :)"
echo "But don't forget to come back, I'll have questions later!"
echo ""

function check_for_easy_install {
    if hash easy_install 2>/dev/null; then
        easy_install_version=$(easy_install --version)
        echo "Found easy_install: $easy_install_version"
    else
        echo "easy_install not found, installing now..."

        if hash apt-get 2>/dev/null; then
        	if [[ $1 -eq '-v' ]]; then
        		apt-get -y install python-setuptools
        	else
				apt-get -y install python-setuptools > /dev/null
        	fi
        else
        	echo "no apt-get, using curl..."
        	if [[ $1 -eq '-v' ]]; then
        		curl https://bootstrap.pypa.io/ez_setup.py -o - | python
        	else
        		curl https://bootstrap.pypa.io/ez_setup.py -o - | python > /dev/null
        	fi
        fi
    fi
}

function check_for_pip {
	if hash pip 2>/dev/null; then
		pip_version=$(pip --version)
		echo "Found pip: $pip_version"
	else
		echo "pip not found, installing now..."
		if [[ $1 -eq '-v' ]]; then
			easy_install pip
		else
			easy_install pip > /dev/null
		fi
	fi
}

function check_for_isstreamer {
	isstreamer=$(pip list | grep ISStreamer)
	if [ -z "$isstreamer" ]; then
		echo "ISStreamer not found, installing..."
		pip install ISStreamer --pre
	else
		echo "ISStreamer found, updating..."
		pip install --upgrade ISStreamer --pre
	fi
}

function download_script {
	echo -n "Enter www.initialstate.com user email: "
	read username < /dev/tty 
	echo -n "Enter www.initialstate.com password [input hidden]: "
	read -s password < /dev/tty
	echo ""

	if [ -z "$example_location" ]; then
		example_location="./is_example.py"
	fi

	python_example=$(curl -X POST "https://dev-api.initialstate.com/api/v1/python/jump_start" -H "X-USER: $username" -H "X-SEC: $password" -H "Accept-Content: text/plain" -H "X-BUCKET: $bucket" -m 30 -d "" -s)
	
	if [ "$python_example" = "INVALID_CREDENTIALS" ]; then
		echo "invalid credentials, let's try that again!"
		download_script
	else
		echo "$python_example" > "$example_location"
	fi
}

function setup_first_script {
	echo -n "Do you want automagically get a script to start? [y/N] "
	read is_wanted < /dev/tty

	if [[ $is_wanted -eq 'y' || $is_wanted -eq 'Y' ]]; then
		echo "Where do you want to save the example? [default: ./is_example.py]: "
		read example_location < /dev/tty

		echo "What do you want to name this project? "
		read bucket < /dev/tty
		download_script
	fi
	
	echo "All done!"
}

check_for_easy_install
check_for_pip
check_for_isstreamer

setup_first_script
