#!/bin/bash

echo "Beginning ISStreamer Python Easy Installation!"
echo "This may take a couple minutes to install, grab some coffee :)"
echo "But don't forget to come back, I'll have questions later!"
echo ""

function check_for_easy_install {
    if hash easy_install 2>/dev/null; then
        easy_install_version=$(easy_install --version)
        echo "Found easy_install: $easy_install_version"
    else
        echo "easy_install not found, installing now..."

        if hash apt-get 2>/dev/null; then
        	if [[ $1 -eq '-v' ]]; then
        		apt-get -y install python-setuptools
        	else
				apt-get -y install python-setuptools > /dev/null
        	fi
        else
        	echo "no apt-get, using curl..."
        	if [[ $1 -eq '-v' ]]; then
        		curl https://bootstrap.pypa.io/ez_setup.py -o - | python
        	else
        		curl https://bootstrap.pypa.io/ez_setup.py -o - | python > /dev/null
        	fi
        fi
    fi
}

function check_for_pip {
	if hash pip 2>/dev/null; then
		pip_version=$(pip --version)
		echo "Found pip: $pip_version"
		pip_version_array=(${pip_version//" "/ })
		pip_version_num=${pip_version_array[1]}
		pip_version_num_array=(${pip_version_num//./ })
		pip_major_version=${pip_version_num_array[0]}
		pip_minor=${pip_version_num_array[1]}
		pip_minor_version_array=(${pip_minor//"rc"/ })
		pip_minor_version=${pip_minor_version_array[0]}

		echo "pip major version: $pip_major_version"
		echo "pip minor version: $pip_minor_version"

		if [ -z "$ISSTREAMER_PRE" ]; then
			ISSTREAMER_PRE=0
		fi
		
		if (( "$ISSTREAMER_PRE" == "1" && "$pip_major_version" >= "1" && "$pip_minor_version" >= "4" ))
		then
			use_pre_flag=1
		else
			use_pre_flag=0
		fi

		echo "use --pre flag: $use_pre_flag"

	else
		echo "pip not found, installing now..."
		if [[ $1 -eq '-v' ]]; then
			easy_install pip
		else
			easy_install pip > /dev/null
		fi
	fi
}

function check_for_isstreamer {
	isstreamer=$(pip list | grep ISStreamer)
	if [ -z "$isstreamer" ]; then
		echo "ISStreamer not found, installing..."

		if (( "$use_pre_flag" == "1" ))
		then
			pip install ISStreamer --pre
		else
			pip install ISStreamer
		fi
	else
		echo "ISStreamer found, updating..."
		if (( "$use_pre_flag" == "1" ))
		then
			pip install --upgrade ISStreamer --pre
		else
			pip install --upgrade ISStreamer
		fi
	fi
}

function download_script {
	echo -n "Enter www.initialstate.com user email: "
	read username < /dev/tty 
	echo -n "Enter www.initialstate.com password [input hidden]: "
	read -s password < /dev/tty
	echo ""

	if [ -z "$example_location" ]; then
		example_location="./is_example.py"
	fi

	python_example=$(curl -X POST "https://api.initialstate.com/api/v1/python/example" -H "X-USER: $username" -H "X-SEC: $password" -H "Accept-Content: text/plain" -m 30 -d "" -s)
	
	if [ "$python_example" = "INVALID_CREDENTIALS" ]; then
		echo "invalid credentials, let's try that again!"
		download_script
	else
		echo "$python_example" > "$example_location"
		loggedin_user=$(logname)
		chown $loggedin_user "$example_location"
	fi
}

function setup_first_script {
	echo -n "Do you want automagically get an example script? [y/N] "
	read is_wanted < /dev/tty

	if [ "$is_wanted" = "y" ] || [ "$is_wanted" = "Y" ]; then
		echo "Where do you want to save the example? [default: ./is_example.py]: "
		read example_location < /dev/tty

		download_script
	fi
	
	echo "All done!"
}

check_for_easy_install
check_for_pip
check_for_isstreamer

setup_first_script
